# render.yaml
services:
  - type: web
    name: qventory
    env: python
    plan: starter        # o free para pruebas (sin disco), starter recomendado
    region: oregon       # elige la región que te convenga
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 -t 120 -b 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /
    autoDeploy: true

    # Disco persistente
    disk:
      name: qventory-data
      mountPath: /var/data
      sizeGB: 1          # ajusta según tus necesidades

    envVars:
      - key: SECRET_KEY
        value: c3f9a4b8e7d12f4a9b6d8c3e5a2f7b1c
      - key: QVENTORY_DB_PATH
        value: /var/data/app.db
      # - key: QVENTORY_SEED_DEMO
      #   value: "0"      # asegúrate de NO seedear en prod
