"""fix auto_relist_history foreign key cascade

Revision ID: 010_fix_auto_relist_cascade
Revises: 009_merge_heads
Create Date: 2025-10-16

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010_fix_auto_relist_cascade'
down_revision = '009_merge_heads'
branch_labels = None
depends_on = None


def upgrade():
    """
    Ensure that auto_relist_history.rule_id has ON DELETE CASCADE
    This allows deleting rules without manually deleting history records
    """
    bind = op.get_bind()

    # Drop existing foreign key constraint
    # The constraint name is auto-generated by SQLAlchemy as: auto_relist_history_rule_id_fkey
    try:
        op.drop_constraint(
            'auto_relist_history_rule_id_fkey',
            'auto_relist_history',
            type_='foreignkey'
        )
    except Exception:
        # Constraint might have different name, try to find it
        pass

    # Recreate with CASCADE
    op.create_foreign_key(
        'auto_relist_history_rule_id_fkey',
        'auto_relist_history',
        'auto_relist_rules',
        ['rule_id'],
        ['id'],
        ondelete='CASCADE'
    )


def downgrade():
    """
    Revert to non-cascading foreign key (not recommended)
    """
    bind = op.get_bind()

    op.drop_constraint(
        'auto_relist_history_rule_id_fkey',
        'auto_relist_history',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'auto_relist_history_rule_id_fkey',
        'auto_relist_history',
        'auto_relist_rules',
        ['rule_id'],
        ['id']
    )
